$modelname "weapons/arc9/darsu_eft/mods/charge_ak_zenit_rp1_LOD0_0.mdl"

$scale 40

// $cdmaterials "models/weapons/arc9/darsu_eft/ak/"
// $cdmaterials "models/weapons/arc9/darsu_eft/shared/"
$cdmaterials "models/weapons/arc9/darsu_eft/mods/"

$bodygroup "body"
{
	studio "charge_ak_zenit_rp1_LOD0_0.smd"
	studio "charge_ak_css_knurled_charging_handle_LOD0_0.smd"
}

$sequence "idle" {
	"Plane.smd"
}