$modelname "weapons/arc9/darsu_eft/mods/ak_gasblocks.mdl"

$scale 40

$cdmaterials "models/weapons/arc9/darsu_eft/ak/"
$cdmaterials "models/weapons/arc9/darsu_eft/shared/"
$cdmaterials "models/weapons/arc9/darsu_eft/mods/"

$bodygroup "body"
{
	studio "gas_block_ak_izhmash_akm_std_LOD0_0.smd"
	studio "gas_block_ak_izhmash_pp-19-01_std_LOD0_0.smd"
	studio "gas_block_ak_molot_vepr_km_vpo_136_LOD0_0.smd"
	studio "gas_block_izhmash_pp-19-01_std_LOD0_0.smd"
}

$sequence "idle" {
	"..\Plane.smd"
}