$modelname "weapons/arc9/darsu_eft/mods/ak_stocks_fold.mdl"

$scale 40

$cdmaterials "models/weapons/arc9/darsu_eft/ak/"
$cdmaterials "models/weapons/arc9/darsu_eft/mods/"
$cdmaterials "models/weapons/arc9_eft_shared/atts/stock/"

$bodygroup "body"
{
	studio "stock_ak74m_izhmash_ak74m_std_LOD0_0.smd"
	studio "stock_ak_caa_akts_ak74_LOD0_0.smd"
	studio "stock_ak_zenit_pt-3_lock_LOD0_0.smd"
	studio "stock_aks74_izhmash_aks74_std_LOD0_0.smd"
	studio "stock_rpk16_izhmash_rpk_stock_tube_LOD0_0.smd"
	studio "stock_aks74u_izhmash_aks74u_std_LOD0_0.smd"
	studio "stock_pp-19-01_izhmash_vityaz_std_LOD0_0.smd"
}

$sequence "idle" {
	"..\Plane.smd"
}